version: '2.2'
services:
  spark-submit:
    network_mode: host
    image: wdps_spark_submit:v1
    volumes:
      - ./src/:/src/
      - ./data/:/data/
      - ./spark/submit/scripts/setup.sh:/setup.sh
      - ./spark/submit/scripts/submit.sh:/submit.sh
      - ./spark/submit/log4j.properties:/spark/conf/log4j.properties
      - ./requirements.txt:/requirements.txt
      - spark_submit_venv:/venv
volumes:
  data01:
    driver: local
  spark_submit_venv:
    driver: local
    
